baseURL = 'https://dmnx64.github.io'
languageCode = 'en-us'
title = 'DMNx64'
theme = "coder-customized"

[params]
  author = "dmnx64"
  description = "My personal notes"
  menu_item_separator = " - "
  colorScheme = "dark"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/dmnx64"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/dmnx64"